### PR TITLE
Changes to build with Stack LTS 12.1

### PR DESCRIPTION
**Pull request by saurabhnanda**
Are you open to publishing this on Stackage?

### CODE REVIEW

**Comment by eliaslfox** [comment]
Yeah, publishing it on stackage would be great. I haven't done that yet, but I'll look into it.

**Comment by eliaslfox** [comment]
Also I'm going to test this, and assuming it builds and the tests pass I'll merge it.

**Comment by saurabhnanda** [comment]
@eliasfox please be aware of `package.yaml` and removal of the cabal file.

**Comment by eliaslfox** [comment]
This looks great, I'll merge it and then make a release. @saurabhnanda, thanks for your help :smile:.

**Pull request merged**
